### ISSUE TITLE
Audit Stackmap Explore Tool for Accessiblity

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/dacs_handbook#116]
### URL
https://princeton.stackmap.com/explore/

Audit two types of pages

- [x] Browse Floorplans Screen - https://princeton.stackmap.com/explore/
- [x] Individual Floorplan Screen - https://princeton.stackmap.com/explore/21

### Acceptance criteria
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

### Notes
- [x] Follow our audit procedure and create an audit report to be distributed to the vendor.

**Comment by christinach** [comment]
@sandbergja and I created this WIP audit report https://docs.google.com/spreadsheets/d/1YArv0Bcs2thFJINIO_T_s8LLyxVHT8Ent2t3CU7YxxY/edit#gid=0

**Comment by christinach** [comment]
@sandbergja and I updated the report with a few more issues. Tomorrow 8/17/23 we will test it with the screenreader.

**Comment by sandbergja** [comment]
@christinach and I completed our testing, including screen reader testing.  Final spreadsheet at https://docs.google.com/spreadsheets/d/1YArv0Bcs2thFJINIO_T_s8LLyxVHT8Ent2t3CU7YxxY/edit#gid=0

**Comment by kevinreiss** [comment]
Thank you! I will pass this on to the vendor.
