### ISSUE TITLE
Build Demo Application with Spring

### ISSUE THREAD

**Issue by christinach** [pulibrary/dacs_handbook#128]
## Notes
[Spring](https://spring.io/projects/spring-framework)

- [x] An application that one can run locally
- [x] Basic README listing dependencies
- [x] Provides a demo API endpoint for the catalog “Bento” option (getting data either from Solr directly or Blacklight API) at /search/catalog?query=[query terms].  [We could use SolrJ](https://solr.apache.org/guide/8_4/using-solrj.html)
- [x] API response should include a count of the total results from the catalog
- [x] API response should include a link to the catalog search, so that a user can continue their search there
- [x] API response should include the first 3 results from the catalog, each with its title, creator, URL, and description.
- [x] Include tests
- [ ] Fill out the evaluation spreadsheet - https://docs.google.com/spreadsheets/d/1M6-dvkwwYHT-x-rGedwbnZ2HEWTXhDD7SGquv0aihrY/edit#gid=0

**Comment by sandbergja** [comment]
Demo application at https://github.com/pulibrary/bento_search_spring_experiment
