### ISSUE TITLE
Build Demo application with Hanami

### ISSUE THREAD

**Issue by christinach** [pulibrary/dacs_handbook#129]
[Hanami](https://hanamirb.org/)

- [x] An application that one can run locally
- [x] Basic README listing dependencies
- [x] Provides a demo API endpoint for the catalog “Bento” option (getting data either from Solr directly or Blacklight API) at /search/catalog?query=[query terms].  
- [x] API response should include a count of the total results from the catalog
- [x] API response should include a link to the catalog search, so that a user can continue their search there
- [x] API response should include the first 3 results from the catalog, each with its title, creator, URL, and description.
- [x] Include tests
- [x] Fill out the evaluation spreadsheet - https://docs.google.com/spreadsheets/d/1M6-dvkwwYHT-x-rGedwbnZ2HEWTXhDD7SGquv0aihrY/edit#gid=0

**Comment by maxkadel** [comment]
Questions from building:
1. How do we want to handle empty searches? They tend to take a long time and don't necessarily give much user value (although I confess I use them all the time in testing)
2. If available, should we include a "score"? It strikes me that this would be helpful in the types of integrations Jon and Esmé suggested (so, if you're on the Catalog, but your search turns up records with very high scores from the maps application, that's when you could suggest the user might want to go there)
