### ISSUE TITLE
Convert DACS Project Spreadsheet into Handbook Page Listing out Projects and their stakeholders

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/dacs_handbook#144]
Current sheet: https://docs.google.com/spreadsheets/d/1fJZ6CE4yq4EyaoeOE__bjEYPUv5xlZVM0bPKfyVAUQw/edit#gid=0

**Comment by sandbergja** [comment]
@kevinreiss and @kelea99 just fyi that I just created a related issue #226

**Comment by kevinreiss** [comment]
Closing in favor of that ticket.
