### ISSUE TITLE
Shut Down Libweb2

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/dacs_handbook#164]
Deprecate this server (libserv55 - libweb2 is an alias) and archive web content SC deem useful. The following three content directorys need review 

- [x] /var/www/htdocs/Music - Music staff have been asked about this content on 3/21
- [x] /var/www/htdocs/Rbsc2 - see [OLD RBSC Inventory](https://docs.google.com/spreadsheets/d/1UsMmbMxyJVr03I6NHJ1449_35_OkJW3SNhdaq0nzCaI/edit#gid=1351235624)
- [x] /var/www/htdocs/libraries/firestone/rbsc/mudd - complete https://github.com/pulibrary/mudd-exhibits/issues/1

**Comment by maxkadel** [comment]
Music staff has confirmed they do not need any of the data from this server.

**Comment by kevinreiss** [comment]
Sara Logue says her team is reviewing the rbsc2 directory this month and will update the inventory spreadsheet by the end of June.

**Comment by beth-german** [comment]
@beth-german review 2nd sheet with Sara

**Comment by kevinreiss** [comment]
Asked SC for update 7/24. Said they'd check in tomorrow morning on where this is at.

**Comment by kevinreiss** [comment]
libweb2 content SC said to retain is quite large ~ 3GB I think we have to put this on a fileshare instead of github.

**Comment by VickieKarasic** [comment]
@kevinreiss will 3GB be the final size, or will this grow? If the final size, we have `lib-fs-prod` where it can live.

**Comment by kevinreiss** [comment]
@VickieKarasic there is also content from lib-fileshare that is linked to catalog records that we should restore, ultimately this all needs to go into figgy but that's going to take awhile. So BTW this 3GB that other data is around  5GB.

**Comment by kevinreiss** [comment]
I'm going to close this ticket and make a new one regarding a fileshare that we can mount on the web.
