### ISSUE TITLE
Run playbook on staging and prod/ Deploy application on staging and production machines

### ISSUE THREAD

**Issue by christinach** [pulibrary/dacs_handbook#165]
1. Pick a repository and add you name next to the checkbox in the following list.
1. Run the playbook against staging. ([Also see docs how to run all the staging playbooks at once using different tags. ](https://github.com/pulibrary/dacs_handbook/blob/main/maintenance.md))
4. Deploy the application to staging.
5. Check that the application is running on staging. 
6. Run the playbook for the specific application against production.
7. Deploy the application to production.

- [x] Orangelight @christinach 
- [x] bibdata @christinach 
- [x] lib-jobs @christinach
- [x] dss @christinach 
- [x] lockers @christinach
- [x] approvals @christinach 
- [x] repec @christinach
- [x] mudd_dbs @christinach
- [x] geaccirc @christinach
- [x] library website and discovery utils - @sandbergja 
- [x] Special Collections - @sandbergja
- [x] friends of the library - @sandbergja
- [x] byzantine translations - @sandbergja
- [x] recap - @sandbergja
- [x] research data - @sandbergja
- [x] pas - @sandbergja
- [x] video reserves - @sandbergja
- [x] allsearch frontend - @sandbergja 
- [x] allsearch api @christinach

**Comment by sandbergja** [comment]
We've run all the playbooks and deployed all the applications! 🥳
