### ISSUE TITLE
Add issue templates to all the application repos

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/dacs_handbook#170]
### Success criteria

- [x] All repos on our [list of repos](https://docs.google.com/spreadsheets/d/1fJZ6CE4yq4EyaoeOE__bjEYPUv5xlZVM0bPKfyVAUQw/edit#gid=0) has the following issue templates, as appropriate.
    - Accessibility
    - Accessibility Audit
    - Bug report
    - Feature request (not needed for legacy systems where we won't add features)
    - Maintenance task
    - Language upgrade (Ruby or PHP)
    - ~~Framework upgrade (not needed for systems that don't use a framework like Rails or Vue)~~
    - UI change (not needed for legacy systems where we won't add features)
- [x] Unless the repository has some specific requirements, the content of the issue template matches the template in orangelight.

## Repositories to check

- [x] Orangelight	https://github.com/pulibrary/orangelight
- [x] Bibdata	https://github.com/pulibrary/bibdata
- [x] Lib Jobs	https://github.com/pulibrary/lib_jobs
- [x] DSS Catalog	https://github.com/pulibrary/dss
- [x] Lockers	https://github.com/pulibrary/lockers_and_study_spaces
- [x] Approvals	https://github.com/pulibrary/approvals
- [x] RePec	https://github.com/pulibrary/repecwp
- [x] Aspace Helpers	https://github.com/pulibrary/aspace_helpers
- [x] GEAC	https://github.com/pulibrary/geaccirc
- [x] libapps	https://github.com/pulibrary/libapps
- [x] Byzantine Translations	https://github.com/pulibrary/byzantine_translations
- [x] Princeton and Slavery	https://github.com/PrincetonUniversityLibrary/pas-craft3
- [x] Marquand Catalogs	https://github.com/pulibrary/marquand-catalogs
- [x] Allsearch frontend	https://github.com/pulibrary/allsearch_frontend
- [x] Allsearch API	https://github.com/pulibrary/allsearch_api

**Comment by maxkadel** [comment]
All unchecked repos have PRs
