### ISSUE TITLE
Check branch protection rules on our repos

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/dacs_handbook#187]
### What maintenance needs to be done

Check [all of the repos we maintain](https://docs.google.com/spreadsheets/d/1fJZ6CE4yq4EyaoeOE__bjEYPUv5xlZVM0bPKfyVAUQw/edit#gid=0) to make sure that the main branch has the same branch protection rules as [pul-it-handbook](https://github.com/pulibrary/pul-it-handbook/settings/branches).

### Why?

The pul-it-handbook rules prevent us from pushing to main from the command line, which is what we want.  All changes should go through pull requests.

**Comment by kevinreiss** [comment]
Went through our spreadsheet: https://docs.google.com/spreadsheets/d/1fJZ6CE4yq4EyaoeOE__bjEYPUv5xlZVM0bPKfyVAUQw/edit?gid=0#gid=0, except for repos marked deprecated.
