### ISSUE TITLE
Add Accounts Page

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/dacs_handbook#19]
List all accounts/services devs on the team need access to.

**Comment by sandbergja** [comment]
Might want to add https://pod.stanford.edu/ -- I saw that @maxkadel hasn't been added yet.

Here is some documentation from POD: https://github.com/pod4lib/aggregator/wiki/Organization-owner's-manual#users-tab

**Comment by sandbergja** [comment]
closed by #20
