### ISSUE TITLE
Run deployments for the workcycle starting on [7/10/2024]

### ISSUE THREAD

**Issue by christinach** [pulibrary/dacs_handbook#214]
#### Orangelight
- [x] Staging
- [x] QA
- [ ] Production

#### Bibdata
- [x] Staging
- [x] QA
- [ ] Production

#### Lib Jobs
- [x] Staging
- [ ] Production

#### DSS
- [x] Staging
- [ ] Production

#### Lockers
- [x] Staging
- [ ] Production

#### Approvals
- [x] Staging
- [ ] Production

#### RePec
- [ ] Staging
- [ ] Production

#### Mudd DB
- [x] Staging
- [ ] Production

#### Aspace Helpers
- [ ] Staging
- [ ] Production

#### GEAC
- [x] Staging
- [ ] Production

#### Library Website
- [ ] Staging
- [ ] Before deploying to production check [Check if end users have changed any settings](https://github.com/pulibrary/pul_library_drupal/wiki/Sync-a-Feature(s)-from-Production)
- [ ] Production

#### Special Collections
- [ ] Staging
- [ ] Production

#### Friends of the Library
- [ ] Staging
- [ ] Production

#### Byzantine Translations
- [ ] Staging
- [ ] Production

#### ReCAP
- [ ] Staging
- [ ] Production

### ResearchData
- [ ] Staging
- [ ] Production

#### Princeton and Slavery
- [ ] Staging
- [ ] Production

#### Video Reserves
- [ ] Staging
- [ ] Production

#### Static Tables
- [ ] Staging
- [ ] Production

#### Allsearch Frontend
- [x] Staging
- [ ] Production

#### Allsearch API
- [x] Staging
- [ ] Production

**Comment by maxkadel** [comment]
Closing in favor of #221
