### ISSUE TITLE
Evaluate options for security checks in CI for each project

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/dacs_handbook#233]
### What maintenance needs to be done?

Check which of the following tools are appropriate for inclusion in our active and maintenance repositories:

* [CodeQL](https://github.com/pulibrary/pul-it-handbook/blob/main/security/security_tools.md#codeql)
* [Semgrep](https://github.com/pulibrary/pul-it-handbook/blob/main/security/security_tools.md#semgrep)
* [Wapiti](https://github.com/pulibrary/pul-it-handbook/blob/main/security/security_tools.md#wapiti)
* [Dastardly](https://github.com/pulibrary/pul-it-handbook/blob/main/security/security_tools.md#burp-suite-and-dastardly)
* [Bearer](https://github.com/pulibrary/pul-it-handbook/blob/main/security/security_tools.md#bearer)

Our repositories in active mode and maintenance mode:

- [ ] Orangelight
- [ ] Bibdata
- [ ] Lib Jobs
- [ ] Aspace helpers
- [ ] Allsearch frontend
- [ ] Allsearch api
- [ ] Lockers
- [ ] DSS
- [ ] Approvals
- [ ] Repec
- [ ] Static tables
- [ ] Lux? (not sure if we should include shared departmental projects in this ticket)
- [ ] Geaccirc
- [ ] PAS
- [ ] Video reserves

If a repository should be using one of these tools (or if it has one that is not a good fit), make a ticket in that repository to add/remove it.

**Comment by christinach** [comment]
Created separate tickets for each tool
