### ISSUE TITLE
Evaluate security check with Dastardly in CI

### ISSUE THREAD

**Issue by christinach** [pulibrary/dacs_handbook#237]
### What maintenance needs to be done?

Check if [Dastardly](https://github.com/pulibrary/pul-it-handbook/blob/main/security/security_tools.md#burp-suite-and-dastardly) is appropriate for inclusion in our active and maintenance repositories?

Our repositories in active mode and maintenance mode:

- [ ] Orangelight
- [ ] Bibdata
- [ ] Lib Jobs
- [ ] Aspace helpers
- [ ] Allsearch frontend
- [ ] Allsearch api
- [ ] Lockers
- [ ] DSS
- [ ] Approvals
- [ ] Repec
- [ ] Static tables
- [ ] Lux? (not sure if we should include shared departmental projects in this ticket)
- [ ] Geaccirc
- [ ] PAS
- [ ] Video reserves

**Comment by kevinreiss** [comment]
@rladdusaw attempted to add this to CI but it didn't work out well. Couldn't get it to successfully run either locally or CI.
