### ISSUE TITLE
Run all the Rails app playbooks this week

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/dacs_handbook#37]
- [x] orangelight -- (Christina)
- [x] bibdata -- (Jane)
- [x] lib_jobs -- (Max)
- [x] dss -- (Max)
- [x] approvals -- (Christina)
- [x] repec -- (Ryan)
- [x] mudd_db -- (Ryan)
- [x] geaccirc -- (Max)
- [x] lockers -- (Jane)

**Comment by sandbergja** [comment]
@rladdusaw did you run the repec playbook?  Just wondering if this ticket can be closed.

**Comment by rladdusaw** [comment]
Got the last one redeployed.
