### ISSUE TITLE
Evaluate Options for Replacing All/Bento Search

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/dacs_handbook#80]
## Supporting documents to review prior to discussion:

- Assessment of current "All" Search usage on the website: https://docs.google.com/document/d/1RGshNflActY5bxSqeBrg20Fskau_CKBbyCQQABVg7ns/edit#heading=h.dpivtjrixeh8
- Description of "current" all options - (https://docs.google.com/spreadsheets/d/1a-_ab9nIj4w3bEvduO8Ngnmt5_6mM13m4iwFHpxzGOY/edit#gid=0)
- Review Recommendations from AUX Review: https://docs.google.com/document/d/1IPhYZlpTNbjtJSZyAMk4baIwyDxcy23AHCxrDhNH7z4/edit
- Bento MVP Requirements: https://docs.google.com/spreadsheets/d/1djxQ31PWr0bxWr1thgmuUchxKEZ6E3qaTJ2LQG_xfYM/edit#gid=0

## Evaluation steps

- [x] Populate decision document template - https://docs.google.com/document/d/1-szVXOadyuVwrNlvMwArSVa40rxuEiMH-7NkK4ISmCE/edit#
- [x] Experiment with new approaches (Optional - if we decide with want to try more than one)
- [x] Make implementation choice for Backend
- [x] Make implementation choice for Frontend - See https://docs.google.com/document/d/13icejSAb6e7zltD5O9NqpornC7jeqP7po6VxkVgyc5w/edit#heading=h.ov0j6ryql781

**Comment by sandbergja** [comment]
We've decided on rails for the backend and Vue for the frontend.
